#
# Module manifest for module 'dbadisa'
#
# Generated by: Chrissy LeMaire
#
# Generated on: 10/28/2019
#
@{
    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # ID used to uniquely identify this module
    GUID              = '27d3f90a-5220-4e78-8565-3b6c39f815a3'

    # Author of this module
    Author            = 'Chrissy LeMaire'

    # Company or vendor of this module
    CompanyName       = 'Chrissy LeMaire'

    # Copyright statement for this module
    Copyright         = '2019 Chrissy LeMaire'

    # Description of the functionality provided by this module
    Description       = 'DISA STIG Automation for SQL Server'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @(
        @{ ModuleName = 'PSFramework'; ModuleVersion = '1.0.19' },
        @{ ModuleName = 'dbatools'; ModuleVersion = '1.0.61' }
        @{ ModuleName = 'dbachecks'; ModuleVersion = '1.2.15' }
    )

    # Script module or binary module file associated with this manifest.
    RootModule        = 'dbadisa.psm1'

    FunctionsToExport = @(
        'Install-DbaDisaStigAudit',
        'Get-DbsStig',
        'Set-DbsAcl'
    )

    PrivateData       = @{
        # PSData is module packaging and gallery metadata embedded in PrivateData
        # It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
        # We had to do this because it's the only place we're allowed to extend the manifest
        # https://connect.microsoft.com/PowerShell/feedback/details/421837
        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category     = 'Security'

            # Keyword tags to help users find this module via navigations and search.
            Tags         = @('security', 'disa', 'stig', 'compliance')

            # The web address of an icon which can be used in galleries to represent this module
            IconUri      = ''

            # Indicates this is a pre-release/testing version of the module.
            IsPrerelease = 'False'
        }
    }
}